name: PHP Tests
on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: CS/PHPStan/PHPUnit"
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        experimental: [false]
        include:
          - php-versions: '8.0'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr, phpcs, phpstan, phpunit
          extensions: redis

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Run PHPCS
        continue-on-error: true
        run: phpcs -q --report=checkstyle lib --standard=PSR12 | cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: phpstan analyse lib -l1

      - name: Run PHPunit
        run: phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

      - name: Collect code coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml